anchor_version = "0.29"

[features]
seeds = false

[programs.localnet]
amm_v3 = "8ZyF28dyVvevYtdDUSRQGgbHtMV8cYZw53oY4c4ZvkgJ"

[registry]
url = "https://github.com/raydium-io/raydium-amm-v3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
